presubmits:
  cert-manager/go-pkcs12:

    - name: pull-cert-manager-go-pkcs12-verify
      always_run: true
      max_concurrency: 8
      decorate: true
      branches:
        - master
      spec:
        containers:
          - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20250327-a3af8ba-1.24
            args:
              - make
              - test
            resources:
              requests:
                cpu: 2
                memory: 4Gi
        dnsPolicy: None
        dnsConfig:
          nameservers:
            - 8.8.8.8
            - 8.8.4.4