periodics:

- name: periodic-testing-close
  interval: 1h
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Closes PRs and issues that are marked 'rotten' and have been inactive for 30d
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager repo:cert-manager/trust-manager
        -label:lifecycle/frozen
        label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/github/token
      - |-
        --comment=Rotten issues close after 30d of inactivity.
        Reopen the issue with `/reopen`.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        /close
      - --ceiling=10
      - --confirm

- name: periodic-testing-rotten
  interval: 1h
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Marks PRs and issues that are marked 'stale' and have been inactive for 30d as 'rotten'
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager repo:cert-manager/trust-manager
        -label:lifecycle/frozen
        label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/github/token
      - |-
        --comment=Stale issues rot after 30d of inactivity.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        Rotten issues close after an additional 30d of inactivity.
        If this issue is safe to close now please do so with `/close`.
        /lifecycle rotten
        /remove-lifecycle stale
      - --ceiling=10
      - --confirm

- name: periodic-testing-stale
  interval: 1h
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Marks PRs and issues that have been inactive for 30d as 'stale'
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager repo:cert-manager/trust-manager
        -label:lifecycle/frozen
        -label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=2160h
      - --token=/etc/github/token
      - |-
        --comment=Issues go stale after 90d of inactivity.
        Mark the issue as fresh with `/remove-lifecycle stale`.
        Stale issues rot after an additional 30d of inactivity and eventually close.
        If this issue is safe to close now please do so with `/close`.
        /lifecycle stale
      - --ceiling=10
      - --confirm

- name: periodic-testing-autobump
  cron: "30 18-23/5 * * 1-5"  # Run at 10:30 and 15:30 PST (18:05 UTC, fall) Mon-Fri
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Creates autobump PRs for the cert-manager/testing repo.
  extra_refs:
  - org: cert-manager
    repo: testing
    base_ref: master
  labels:
    preset-deployer-github-token: "true"
    preset-deployer-ssh-key: "true"
  spec:
    containers:
    - image: us-docker.pkg.dev/k8s-infra-prow/images/generic-autobumper:v20250410-b8e0bd8d4
      command:
      - generic-autobumper
      args:
      - --config=config/autobump-config/testing-autobump-config.yaml
      - --signoff

- name: periodic-testing-label-sync
  cron: "17 * * * *"  # Every hour at 17 minutes past the hour
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs label_sync to synchronize GitHub repo labels with the label config defined in label_sync/labels.yaml.
  extra_refs:
  - org: cert-manager
    repo: testing
    base_ref: master
  spec:
    containers:
    - name: label-sync
      image: gcr.io/k8s-staging-test-infra/label_sync:v20250306-095fc63a16
      command:
      - label_sync
      args:
      - --config=config/labels.yaml
      # TODO: enable label_sync across the whole org
      - --only=cert-manager/cert-manager,cert-manager/website,cert-manager/release,cert-manager/istio-csr,cert-manager/approver-policy,cert-manager/trust-manager,cert-manager/issuer-lib,cert-manager/csi-driver,cert-manager/csi-driver-spiffe,cert-manager/openshift-routes,cert-manager/cert-manager-olm,cert-manager/webhook-lib,cert-manager/csi-lib,cert-manager/sample-external-issuer,cert-manager/cmctl,cert-manager/infrastructure,cert-manager/testing,cert-manager/makefile-modules,cert-manager/helm-tool,cert-manager/image-tool,cert-manager/community,cert-manager/webhook-example,cert-manager/org,cert-manager/base-images,cert-manager/klone,cert-manager/boilersuite,cert-manager/google-cas-issuer
      - --debug
      - --confirm
      - --github-app-id=$(GITHUB_APP_ID)
      - --github-app-private-key-path=/etc/github/cert
      - --github-endpoint=http://ghproxy.default
      - --github-endpoint=https://api.github.com
      env:
      - name: GITHUB_APP_ID
        valueFrom:
          secretKeyRef:
            name: github-app-token
            key: appid
      volumeMounts:
      - name: github-app-token
        mountPath: /etc/github
        readOnly: true
    volumes:
    - name: github-app-token
      secret:
        secretName: github-app-token

- name: periodic-testing-branchprotector
  cron: "54 * * * *"  # Every hour at 54 minutes past the hour
  cluster: prow-trusted
  decorate: true
  decoration_config:
    timeout: 5h
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs Prow's branchprotector to apply configured GitHub status context requirements and merge policies.
  extra_refs:
  - org: cert-manager
    repo: testing
    base_ref: master
  spec:
    containers:
    - name: branchprotector
      image: us-docker.pkg.dev/k8s-infra-prow/images/branchprotector:v20250410-b8e0bd8d4
      command:
      - branchprotector
      args:
      - --config-path=config/config.yaml
      - --job-config-path=config/jobs
      - --confirm
      - --github-app-id=$(GITHUB_APP_ID)
      - --github-app-private-key-path=/etc/github/cert
      - --github-endpoint=http://ghproxy.default
      - --github-endpoint=https://api.github.com
      env:
      - name: GITHUB_APP_ID
        valueFrom:
          secretKeyRef:
            name: github-app-token
            key: appid
      volumeMounts:
      - name: github-app-token
        mountPath: /etc/github
        readOnly: true
    volumes:
    - name: github-app-token
      secret:
        secretName: github-app-token
