periodics:

- name: periodic-testing-close
  interval: 1h
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Closes PRs and issues that are marked 'rotten' and have been inactive for 2y
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager repo:cert-manager/trust-manager
        -label:lifecycle/frozen
        label:lifecycle/rotten
      - --updated=17520h # 2 years
      - --token=/etc/github/token
      - |-
        --comment=Rotten issues close after 2y of inactivity.
        Reopen the issue with `/reopen`.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        /close
      - --ceiling=10
      - --confirm

- name: periodic-testing-rotten
  interval: 1h
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Marks PRs and issues that are marked 'stale' and have been inactive for 1.5y as 'rotten'
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager repo:cert-manager/trust-manager
        -label:lifecycle/frozen
        label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=13140h # 1.5 years
      - --token=/etc/github/token
      - |-
        --comment=Stale issues rot after 1.5y of inactivity.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        Rotten issues close after an additional 6m of inactivity.
        If this issue is safe to close now please do so with `/close`.
        /lifecycle rotten
        /remove-lifecycle stale
      - --ceiling=10
      - --confirm

- name: periodic-testing-stale
  interval: 1h
  cluster: prow-trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Marks PRs and issues that have been inactive for 1y as 'stale'
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager repo:cert-manager/trust-manager
        -label:lifecycle/frozen
        -label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=8760h # 1 year
      - --token=/etc/github/token
      - |-
        --comment=Issues go stale after 1y of inactivity.
        Mark the issue as fresh with `/remove-lifecycle stale`.
        Stale issues rot after an additional 6m of inactivity and eventually close.
        If this issue is safe to close now please do so with `/close`.
        /lifecycle stale
      - --ceiling=10
      - --confirm
