periodics:

- name: periodic-testing-close
  interval: 1h
  cluster: trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Closes PRs and issues that are marked 'rotten' and have been inactive for 30d
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240409-13cd3acf7e
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager
        -label:lifecycle/frozen
        label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/github/token
      - |-
        --comment=Rotten issues close after 30d of inactivity.
        Reopen the issue with `/reopen`.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        /close
      - --ceiling=10
      - --confirm

- name: periodic-testing-rotten
  interval: 1h
  cluster: trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Marks PRs and issues that are marked 'stale' and have been inactive for 30d as 'rotten'
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240409-13cd3acf7e
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager
        -label:lifecycle/frozen
        label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/github/token
      - |-
        --comment=Stale issues rot after 30d of inactivity.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        Rotten issues close after an additional 30d of inactivity.
        If this issue is safe to close now please do so with `/close`.
        /lifecycle rotten
        /remove-lifecycle stale
      - --ceiling=10
      - --confirm

- name: periodic-testing-stale
  interval: 1h
  cluster: trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Marks PRs and issues that have been inactive for 30d as 'stale'
  labels:
    preset-deployer-github-token: "true"
  spec:
    containers:
    - image: gcr.io/k8s-prow/commenter:v20240409-13cd3acf7e
      command:
      - commenter
      args:
      - |-
        --query=repo:cert-manager/cert-manager
        -label:lifecycle/frozen
        -label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=2160h
      - --token=/etc/github/token
      - |-
        --comment=Issues go stale after 90d of inactivity.
        Mark the issue as fresh with `/remove-lifecycle stale`.
        Stale issues rot after an additional 30d of inactivity and eventually close.
        If this issue is safe to close now please do so with `/close`.
        /lifecycle stale
      - --ceiling=10
      - --confirm

- name: periodic-testing-autobump
  cron: "30 18-23/5 * * 1-5"  # Run at 10:30 and 15:30 PST (18:05 UTC, fall) Mon-Fri
  cluster: trusted
  decorate: true
  annotations:
    testgrid-dashboards: cert-manager-testing-janitors
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Creates autobump PRs for the cert-manager/testing repo.
  extra_refs:
  - org: cert-manager
    repo: testing
    base_ref: master
  labels:
    preset-deployer-github-token: "true"
    preset-deployer-ssh-key: "true"
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20240415-7013691e3
      command:
      - generic-autobumper
      args:
      - --config=config/autobump-config/testing-autobump-config.yaml
      - --signoff
