presubmits:
  cert-manager/webhook-cert-lib:

  - name: pull-cert-manager-webhook-cert-lib-verify
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20250327-af35b2b-bookworm
        args:
        - runner
        - make
        - vendor-go
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-webhook-cert-lib-test
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20250327-af35b2b-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-unit
        - test-integration
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-webhook-cert-lib-e2e
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20250327-af35b2b-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
