presubmits:
  jetstack/cert-manager:

  - name: pull-cert-manager-bazel
    always_run: true
    cluster: gke
    context: pull-cert-manager-bazel
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - release-1.2
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-056d642-2.2.0
        args:
        - runner
        - bazel
        - test
        - //...
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-bazel-experimental
    always_run: false
    optional: true
    cluster: gke
    context: pull-cert-manager-bazel-experimental
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - release-1.2
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-experimental
        args:
        - runner
        - bazel
        - test
        - //...
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  # Helm chart verification currently requires Docker.
  # We maintain a standalone presubmit for running this.
  # See https://github.com/helm/chart-testing/issues/53
  - name: pull-cert-manager-chart
    always_run: true
    cluster: gke
    context: pull-cert-manager-chart
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - release-1.2
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-056d642-2.2.0
        args:
        - runner
        - make
        - verify_chart
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-deps
    always_run: true
    cluster: gke
    context: pull-cert-manager-deps
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.2
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-056d642-2.2.0
        args:
        - runner
        - make
        - verify_deps
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-16
    cluster: gke
    context: pull-cert-manager-e2e-v1-16
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.2
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-056d642-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.16"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-17
    cluster: gke
    context: pull-cert-manager-e2e-v1-17
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.2
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-056d642-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.17"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-19
    cluster: gke
    context: pull-cert-manager-e2e-v1-19
    optional: false
    always_run: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.2
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-056d642-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.19"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-20
    cluster: gke
    context: pull-cert-manager-e2e-v1-20
    optional: false
    always_run: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.1
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-056d642-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.20"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
