presubmits:
  cert-manager/trust-manager-csi-driver:

    - name: pull-trust-manager-csi-driver-verify
      decorate: true
      always_run: true
      labels:
        preset-go-cache: "true"
        preset-local-cache: "true"
      spec:
        containers:
          - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20250327-af35b2b-bookworm
            args:
              - runner
              - make
              - vendor-go
              - verify
            resources:
              requests:
                cpu: 1
                memory: 1Gi
        dnsPolicy: None
        dnsConfig:
          nameservers:
            - 8.8.8.8
            - 8.8.4.4

    - name: pull-trust-manager-csi-driver-test
      decorate: true
      always_run: true
      labels:
        preset-go-cache: "true"
        preset-local-cache: "true"
      spec:
        containers:
          - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20250327-af35b2b-bookworm
            args:
              - runner
              - make
              - vendor-go
              - test-unit
            resources:
              requests:
                cpu: 1
                memory: 1Gi
        dnsPolicy: None
        dnsConfig:
          nameservers:
            - 8.8.8.8
            - 8.8.4.4
