name: image-builder # Name of the image to be built

variants:
  gcloud-516:
    arguments:
      BASE_IMAGE: "europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20260120-31ee990-1.25"
      CLOUD_SDK_VERSION: "516.0.0"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${CLOUD_SDK_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${CLOUD_SDK_VERSION}
