presubmits:
  cert-manager/website:

  - name: pull-cert-manager-website-verify
    always_run: true
    context: pull-cert-manager-website-verify
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - ^master$
    - ^release-next$
    - ^release-1\.[0-9]+$
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: "eu.gcr.io/jetstack-build-infra-images/golang-nodejs:20221017-bcd2286-1.17"
        args:
        - ./scripts/verify-release
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
