presubmits:

  cert-manager/org:

  - name: pull-org-verify
    always_run: true
    max_concurrency: 4
    decorate: true
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20250327-a3af8ba-1.24
        args:
        - runner
        - make
        - verify
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
