presubmits:
  cert-manager/boilersuite:
  - name: pull-cert-manager-boilersuite-verify
    always_run: true
    max_concurrency: 2
    decorate: true
    annotations:
      testgrid-create-test-group: 'false'
    labels:
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20250327-a3af8ba-1.24
        args:
        - runner
        - make
        - test-all
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
