name: golang-nodejs # Name of the image to be built

variants:
  "1.17":
  arguments:
      BASE_IMAGE: "node:16.3.0"
      GO_VERSION: "1.17"
  "1.16.6":
    arguments:
      BASE_IMAGE: "node:16.3.0"
      GO_VERSION: "1.16.6"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${GO_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${GO_VERSION}
