name: prow-controller-manager-spot # Name of the image to be built

variants:
  latest:
    arguments:
      BUILDER_IMAGE: "europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20250327-a3af8ba-1.24"
      BASE_IMAGE: "quay.io/jetstack/base-static@sha256:ba3cff0a4cacc5ae564e04c1f645000e8c9234c0f4b09534be1dee7874a42141"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}
- ${_REGISTRY}/${_NAME}:latest
